### PR TITLE
Fix ghooks call and replace with husky as is depreciated 

### PR DESCRIPTION
**Pull request by SteveALee**

### CODE REVIEW

**Comment by jvanbruegge** [comment]
@SteveALee sorry for the merge conflict :)

**Comment by SteveALee** [comment]
@jvanbruegge did you just add the precommit? The other line seems unchanged

**Comment by jvanbruegge** [comment]
yeah, but I just noticed that precommit is not ideal
the formatted code does not get added

**Comment by SteveALee** [comment]
OK I resolved the clash but won't commit. Over to you :)

**Pull request closed without merging**
